export const ENGINE_VERSION = 2 as const;
export * from "./types";
export * from "./sizing";
export * from "./fonts";
export { displayText } from "./text";
export { fitText, type TextMeasurer } from "./textFit";
export { defaultWording, ordinalSuffix, resolveLines } from "./wording";
export { collage, type TemplateContext } from "./templates/collage";
export { expand, applyOverrides } from "./expand";
export { setFonts } from "./setFonts";
