import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fontFaceCss, fontSpecs } from "@/engine/render/browser/fontFaces";
import { CURATED_FONTS, FONT_REGISTRY } from "@/engine";

describe("fontFaceCss", () => {
  it("declares every curated family with display: block", () => {
    const css = fontFaceCss();
    for (const f of CURATED_FONTS) expect(css).toContain(`font-family: "${f}"`);
    const faces = CURATED_FONTS.flatMap(f => FONT_REGISTRY[f].faces);
    expect(css.match(/@font-face/g)?.length).toBe(faces.length);
    expect(css).toContain("font-display: block");
    // One rule per static face, at its exact weight — no synthesised bold, no weight range.
    expect(css).toContain(`url("/fonts/Fredoka-Regular.ttf") format("truetype"); font-weight: 400`);
    expect(css).toContain(`url("/fonts/Fredoka-Bold.ttf") format("truetype"); font-weight: 700`);
    expect(css).toContain(`url("/fonts/Baloo2-ExtraBold.ttf") format("truetype"); font-weight: 900`);
    expect(css).not.toMatch(/font-weight: \d+ \d+/);
  });
});

describe("src/app/fonts.css", () => {
  // The committed sheet is the only thing keeping the browser's weight selection aligned with the
  // print renderer, and nothing regenerates it at build time. A FONT_REGISTRY change without
  // `pnpm gen:fonts` has to fail here rather than drift silently.
  it("is exactly what gen:fonts would write today", () => {
    const file = readFileSync(path.join(__dirname, "..", "..", "src", "app", "fonts.css"), "utf8");
    const header = "/* generated by scripts/gen-font-css.ts */\n";
    expect(file.startsWith(header)).toBe(true);
    expect(file.slice(header.length)).toBe(`${fontFaceCss()}\n`);
  });
});

describe("fontSpecs", () => {
  // This is the whole point of loading on demand: the editor must ask the browser for the faces
  // its design uses, not for all nine. A regression here is a megabyte in front of the first paint.
  it("names only the faces the given families ship", () => {
    expect(fontSpecs(["Chewy"])).toEqual(['400 32px "Chewy"']);
    expect(fontSpecs(["Baloo 2"])).toEqual(['400 32px "Baloo 2"', '700 32px "Baloo 2"', '900 32px "Baloo 2"']);
  });

  it("is far short of the whole registry for a one-family design", () => {
    const all = CURATED_FONTS.flatMap(f => FONT_REGISTRY[f].faces).length;
    expect(fontSpecs(["Fredoka"]).length).toBeLessThan(all);
  });

  it("skips a family that is not curated rather than throwing", () => {
    expect(fontSpecs(["Comic Sans MS", "Chewy"])).toEqual(['400 32px "Chewy"']);
  });
});
