import { writeFileSync } from "node:fs";
import path from "node:path";
import { fontFaceCss } from "../src/engine/render/browser/fontFaces";

const OUT_FILE = path.join(__dirname, "..", "src", "app", "fonts.css");

const css = `/* generated by scripts/gen-font-css.ts */\n${fontFaceCss()}\n`;
writeFileSync(OUT_FILE, css);
console.log(`wrote ${OUT_FILE}`);
